let g:gruvbox_invert_selection = '0'
" gruvbox_contrast = soft, medium, hard
let g:gruvbox_contrast_dark = 'soft'
" let g:gruvbox_contrast_light = 'soft'
let g:gruvbox_italic = '1'
let g:gruvbox_italicize_comments = '1'
let g:gruvbox_bold = '1'
" let g:gruvbox_termcolors = '256'
let g:gruvbox_sign_column = 'bg1'
