let g:sonokai_style = 'default'
let g:sonokai_disablt_italic_comment = 0
let g:sonokai_enable_italic = 1
let g:sonokai_cursor = 'yellow'
let g:sonokai_current_word = 'grey background'
let g:sonokai_transparent_background = 0
let g:sonokai_menu_selection_background = 'green'
let g:sonokai_show_eob = 1
let g:sonokai_diagnostic_text_highlight = 1
let g:sonokai_diagnostic_line_highlight = 1
